version: "3.6"

services:
  s3_service:
    build:
      context: ./s3_service
    env_file:
      - ./s3_service/.env
    volumes:
      - ./s3_service/logs:/app/logs

  test_postgres:
    image: postgres:latest
    env_file:
      - ./psql/.test_env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5433"

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - memes-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  public_api:
    build:
      context: ./public_api
    ports:
      - "8000:8000"
    env_file:
      - ./public_api/.env
    volumes:
      - ./public_api/logs:/app/logs
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

volumes:
  memes-data: